module.exports = {
      "name": "",
      "password": "",
      "role": 0,
      "topics": [
        "Competitive Landscape",
        "Top Results",
        "Winning Matters",
        "Competition",
        "Proof points",
        "Understanding Our Business",
        "Understanding Our Customer",
        "Understanding Our Client's Business",
        "Data Matters",
        "Planning Estimates",
        "Results Matter",
        "Go Above What's Required",
        "Not The Obvious",
        "Alternative",
        "Beautiful",
        "Open To New Ideas",
        "Easier To Understand",
        "Simplicity",
        "Different",
        "Make Someone Smile",
        "Willing To Take A Risk",
        "Put In The Time",
        "Responsibility",
        "Take Extra Time To Check Your Work",
        "Commitment To Excellence",
        "Extra Effort",
        "It's My Job",
        "Accountability",
        "Pride of Ownership",
        "Better Than The Last Time",
        "Peer Review",
        "Creating Good Work Habits",
        "something",
        "Polished",
        "Commitment to Excellence",
        "Not Defensive",
        "Clarity",
        "Finding Answers",
        "The Next Question's Answer",
        "Transparency",
        "Energetic",
        "We Matter",
        "It's My Problem",
        "Pride",
        "Teamwork",
        "Never Let Someone Down",
        "No Ambiguity"
      ],
      "categories": ["Business Intelligence","Creativity & Innovation","Quality & Ownership","Communication & Leadership"],
      "quarters": ["Q1","Q2","Q3","Q4"],
      "priorities": ["none", "low","high","none"],
      "clients": [{
        "name" : "Perfect Sense Digital",
        "image" : "http://profile.ak.fbcdn.net/hprofile-ak-snc4/211197_190286394354404_6947872_n.jpg"
      },{
        "name" : "SnagFilms",
        "image" : "http://www.newsinfilm.com/wp-content/uploads/2009/10/snagfilms_square.gif"
      }],
      "notes": [{
        "name" : "First Note!",
        "clients" : [0],
        "category" : 0,
        "priorities" : [0,2],
        "date" : "2011-10-05T00:45:00.174Z",
        "text" : "This is your first note! Welcome to the Perfect Sense EcoSystem",
        "topics" : [1,2,3],
        "id" : "1317775500174"
      },{
        "name" : "Easy to use...",
        "clients" : [1],
        "category" : 1,
        "priorities" : [2],
        "date" : "2011-12-05T00:15:00.174Z",
        "text" : "Adding, viewing, and editing a note is as easy as clicking the appropriate icons.",
        "topics" : "",
        "id" : "1317828130834"
      }]
};